import { TaskItem } from '../types';

/**
 * Tâches officielles et primes d'activité AirProds (12 tâches officielles)
 */
export const OFFICIAL_TASKS: TaskItem[] = [
  {
    id: 'task_inv_3',
    title: 'Invitez 3 investisseurs de niveau 1',
    description: 'Parrainez 3 investisseurs directs de niveau 1 ayant activé au moins un pack AirProds.',
    category: 'referral',
    targetType: 'level1_investors_count',
    targetValue: 3,
    reward: 1000,
    rewardType: 'one_time',
    isActive: true,
    order: 1,
    iconName: 'Users'
  },
  {
    id: 'task_inv_10',
    title: 'Invitez 10 investisseurs de niveau 1',
    description: 'Parrainez 10 investisseurs directs de niveau 1 ayant activé au moins un pack AirProds.',
    category: 'referral',
    targetType: 'level1_investors_count',
    targetValue: 10,
    reward: 3000,
    rewardType: 'one_time',
    isActive: true,
    order: 2,
    iconName: 'Users'
  },
  {
    id: 'task_inv_30',
    title: 'Invitez 30 investisseurs de niveau 1',
    description: 'Parrainez 30 investisseurs directs de niveau 1 ayant activé au moins un pack AirProds.',
    category: 'referral',
    targetType: 'level1_investors_count',
    targetValue: 30,
    reward: 10000,
    rewardType: 'one_time',
    isActive: true,
    order: 3,
    iconName: 'Award'
  },
  {
    id: 'task_buy_vip4',
    title: 'Achetez VIP4 AirProds',
    description: 'Activez la formule technologique VIP4 AirProds (45 000 XOF) pour débloquer votre prime.',
    category: 'purchase',
    targetType: 'vip_purchase',
    targetValue: 4,
    targetVipLevel: 4,
    reward: 500,
    rewardType: 'one_time',
    isActive: true,
    order: 4,
    iconName: 'Zap'
  },
  {
    id: 'task_buy_vip5',
    title: 'Achetez VIP5 AirProds',
    description: 'Activez la formule technologique VIP5 AirProds (100 000 XOF) pour percevoir votre prime.',
    category: 'purchase',
    targetType: 'vip_purchase',
    targetValue: 5,
    targetVipLevel: 5,
    reward: 1000,
    rewardType: 'one_time',
    isActive: true,
    order: 5,
    iconName: 'Zap'
  },
  {
    id: 'task_buy_vip6',
    title: 'Achetez VIP6 AirProds',
    description: 'Activez la formule technologique VIP6 AirProds (250 000 XOF) pour percevoir votre prime.',
    category: 'purchase',
    targetType: 'vip_purchase',
    targetValue: 6,
    targetVipLevel: 6,
    reward: 2500,
    rewardType: 'one_time',
    isActive: true,
    order: 6,
    iconName: 'ShieldCheck'
  },
  {
    id: 'task_buy_vip7',
    title: 'Achetez VIP7 AirProds',
    description: 'Activez la formule technologique VIP7 AirProds (500 000 XOF) pour percevoir votre prime.',
    category: 'purchase',
    targetType: 'vip_purchase',
    targetValue: 7,
    targetVipLevel: 7,
    reward: 5000,
    rewardType: 'one_time',
    isActive: true,
    order: 7,
    iconName: 'ShieldCheck'
  },
  {
    id: 'task_buy_vip8',
    title: 'Achetez VIP8 AirProds',
    description: 'Activez la formule technologique VIP8 AirProds (1 000 000 XOF) pour percevoir votre prime.',
    category: 'purchase',
    targetType: 'vip_purchase',
    targetValue: 8,
    targetVipLevel: 8,
    reward: 10000,
    rewardType: 'one_time',
    isActive: true,
    order: 8,
    iconName: 'Crown'
  },
  {
    id: 'task_buy_vip9',
    title: 'Achetez VIP9 AirProds',
    description: 'Activez la formule de prestige VIP9 AirProds (2 000 000 XOF) pour percevoir votre prime suprême.',
    category: 'purchase',
    targetType: 'vip_purchase',
    targetValue: 9,
    targetVipLevel: 9,
    reward: 20000,
    rewardType: 'one_time',
    isActive: true,
    order: 9,
    iconName: 'Crown'
  },
  {
    id: 'task_team_400k',
    title: 'Investissement d’équipe de 400 000 XOF',
    description: 'Volume cumulé d’investissements de votre équipe atteignant 400 000 XOF → Salaire quotidien de 500 XOF.',
    category: 'team_salary',
    targetType: 'team_investment_amount',
    targetValue: 400000,
    reward: 500,
    rewardType: 'daily_salary',
    isActive: true,
    order: 10,
    iconName: 'TrendingUp'
  },
  {
    id: 'task_team_1m',
    title: 'Investissement d’équipe de 1 000 000 XOF',
    description: 'Volume cumulé d’investissements de votre équipe atteignant 1 000 000 XOF → Salaire quotidien de 1 000 XOF.',
    category: 'team_salary',
    targetType: 'team_investment_amount',
    targetValue: 1000000,
    reward: 1000,
    rewardType: 'daily_salary',
    isActive: true,
    order: 11,
    iconName: 'TrendingUp'
  },
  {
    id: 'task_team_3m',
    title: 'Investissement d’équipe de 3 000 000 XOF',
    description: 'Volume cumulé d’investissements de votre équipe atteignant 3 000 000 XOF → Salaire quotidien (configurable par l’administrateur).',
    category: 'team_salary',
    targetType: 'team_investment_amount',
    targetValue: 3000000,
    reward: 3000,
    rewardType: 'daily_salary',
    isActive: true,
    order: 12,
    iconName: 'Trophy'
  }
];
